/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   client_to_server__init
                     (ClientToServer         *message)
{
  static ClientToServer init_value = CLIENT_TO_SERVER__INIT;
  *message = init_value;
}
size_t client_to_server__get_packed_size
                     (const ClientToServer *message)
{
  assert(message->base.descriptor == &client_to_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_to_server__pack
                     (const ClientToServer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_to_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_to_server__pack_to_buffer
                     (const ClientToServer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_to_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientToServer *
       client_to_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientToServer *)
     protobuf_c_message_unpack (&client_to_server__descriptor,
                                allocator, len, data);
}
void   client_to_server__free_unpacked
                     (ClientToServer *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &client_to_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_to_client__init
                     (ServerToClient         *message)
{
  static ServerToClient init_value = SERVER_TO_CLIENT__INIT;
  *message = init_value;
}
size_t server_to_client__get_packed_size
                     (const ServerToClient *message)
{
  assert(message->base.descriptor == &server_to_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_to_client__pack
                     (const ServerToClient *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_to_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_to_client__pack_to_buffer
                     (const ServerToClient *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_to_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerToClient *
       server_to_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerToClient *)
     protobuf_c_message_unpack (&server_to_client__descriptor,
                                allocator, len, data);
}
void   server_to_client__free_unpacked
                     (ServerToClient *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &server_to_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue client_to_server__type__enum_values_by_number[4] =
{
  { "LOGIN", "CLIENT_TO_SERVER__TYPE__LOGIN", 0 },
  { "DISC", "CLIENT_TO_SERVER__TYPE__DISC", 1 },
  { "CHAT", "CLIENT_TO_SERVER__TYPE__CHAT", 2 },
  { "QUERY", "CLIENT_TO_SERVER__TYPE__QUERY", 3 },
};
static const ProtobufCIntRange client_to_server__type__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex client_to_server__type__enum_values_by_name[4] =
{
  { "CHAT", 2 },
  { "DISC", 1 },
  { "LOGIN", 0 },
  { "QUERY", 3 },
};
const ProtobufCEnumDescriptor client_to_server__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientToServer.Type",
  "Type",
  "ClientToServer__Type",
  "",
  4,
  client_to_server__type__enum_values_by_number,
  4,
  client_to_server__type__enum_values_by_name,
  1,
  client_to_server__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor client_to_server__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientToServer, type),
    &client_to_server__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientToServer, str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_min",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ClientToServer, has_id_min),
    offsetof(ClientToServer, id_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_max",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ClientToServer, has_id_max),
    offsetof(ClientToServer, id_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_to_server__field_indices_by_name[] = {
  3,   /* field[3] = id_max */
  2,   /* field[2] = id_min */
  1,   /* field[1] = str */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange client_to_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor client_to_server__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientToServer",
  "ClientToServer",
  "ClientToServer",
  "",
  sizeof(ClientToServer),
  4,
  client_to_server__field_descriptors,
  client_to_server__field_indices_by_name,
  1,  client_to_server__number_ranges,
  (ProtobufCMessageInit) client_to_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue server_to_client__code__enum_values_by_number[2] =
{
  { "OK", "SERVER_TO_CLIENT__CODE__OK", 0 },
  { "NOK", "SERVER_TO_CLIENT__CODE__NOK", 1 },
};
static const ProtobufCIntRange server_to_client__code__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex server_to_client__code__enum_values_by_name[2] =
{
  { "NOK", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor server_to_client__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ServerToClient.Code",
  "Code",
  "ServerToClient__Code",
  "",
  2,
  server_to_client__code__enum_values_by_number,
  2,
  server_to_client__code__enum_values_by_name,
  1,
  server_to_client__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor server_to_client__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ServerToClient, has_code),
    offsetof(ServerToClient, code),
    &server_to_client__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ServerToClient, n_str),
    offsetof(ServerToClient, str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_to_client__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = str */
};
static const ProtobufCIntRange server_to_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor server_to_client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerToClient",
  "ServerToClient",
  "ServerToClient",
  "",
  sizeof(ServerToClient),
  2,
  server_to_client__field_descriptors,
  server_to_client__field_indices_by_name,
  1,  server_to_client__number_ranges,
  (ProtobufCMessageInit) server_to_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
